//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureShop.Modules
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Furniture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Furniture()
        {
            this.Orders = new HashSet<Order>();
        }

        public string GetPhoto
        {
            get
            {
                return $@"{Directory.GetCurrentDirectory()}\Images\{Photo}";
            }
        }

        public int GetSale
        {
            get
            {
                if (Sale == 5)
                {
                    return 5;
                }
                else if (Sale == 10)
                {
                    return 10;
                }
                else if (Sale == 15)
                {
                    return 15;
                }
                else if (Sale == 20)
                {
                    return 20;
                }
                else if (Sale == 25)
                {
                    return 25;
                }
                else
                {
                    return 0;
                }
            }
        }

        public string GetColor
        {
            get
            {
                if (Sale > 0)
                    return "#93c496";
                else
                    return "#ffffff";
            }
        }

        public double GetPrice
        {
            get
            {
                if (GetSale > 0)
                {
                    return Price * (1 - (GetSale * 0.01));
                }
                else
                {
                    return Price;
                }
            }
        }

        public string GetAvaible
        {
            get
            {
                if (Avaible == 1)
                {
                    return "Товар в наличии";
                }
                else
                {
                    return "Товара нет в наличии";
                }
            }
        }

        public int FurnitureID { get; set; }
        public int FurnitureTypeID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Photo { get; set; }
        public int Avaible { get; set; }
        public int ColorID { get; set; }
        public int Sale { get; set; }
        public int Lenght { get; set; }
        public int Width { get; set; }
        public int Height { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual FurnitureType FurnitureType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
